TARGET = huemul

SRC = main.cpp \
    core.cpp \
    io.cpp \
    features.cpp \
    training.cpp

INCLUDE_PATH = src

# LIB_PATH_RELEASE = ./lib

# LIB_PATH_DEBUG = ./lib

LIB = boost_iostreams \
			armadillo


include build.mk
